---
#-------------------------------
# Site Settings
title: Node.js SaaS Boilerplate with React - Volca
logo: /images/logo-light.svg
author: Volca
description: Create your SaaS using proven Node and React patterns that accelerate your development and deployment speed.

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    - title: Launch
      url: "/launch/"
    - title: Docs
      url: "/docs/"
    - title: "Blog"
      url: "/blog/"

#-------------------------------
# Hero Settings
hero:
  hero__title: Node.js SaaS Boilerplate with React
  hero__description: Create your SaaS using proven Node and React patterns that accelerate your development and deployment speed.

#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Features
  portfolio__gallery:
    - icon: ion-ios-build
      title: CI/CD
      description: Deploy with confidence from the start with a solid CI/CD setup
      link: /cicd

    - icon: ion-ios-lock
      title: Secure
      description: Built with best practice security
      link: "#"

    - icon: ion-ios-card
      title: Subscriptions
      description: Enable your users to subscribe to your service
      link: "#"

    - icon: ion-ios-briefcase
      title: Projects
      description: Enable your users to create projects and invite their team
      link: "#"

    - icon: ion-ios-key
      title: Authentication
      description: Secure and reliable authentication out of the box
      link: "#"

    - icon: ion-ios-pulse
      title: Monitoring
      description: Make sure your SaaS is running smoothly at all times
      link: "#"

    - icon: ion-ios-search
      title: Logging
      description: Find and remedy production issues quickly
      link: "#"

    - icon: ion-ios-cash
      title: Free Tier
      description: Free at rest infrastructure - no usage, no cost
      link: "#"

    - icon: ion-ios-code
      title: Open Source
      description: Our core functionality is available open source
      link: /open-source
      
    - icon: ion-ios-cloud
      title: Serverless
      description: Focus on creating a great product instead of managing servers
      link: /serverless

#-------------------------------
# FAQ Settings
faq:
  - title: What is Volca?
    description: Volca is a code template for SaaS products that give you everything you need to start building the features that make your product unique. Volca is powered by a NodeJS API and a React frontend built by developers with over 10 years of experience building and running applications with this technology stack.

  - title: Who is Volca for?
    description: In short, Volca is built for developers who want to create software products fast. The template can be used by beginner and experienced developers alike and is built using the industry best practices with developer experience as a top priority.

  - title: How do I get started creating a product with Volca?
    description: We have worked hard on documenting Volca and creating tutorials that are easy to follow. If you find yourself stuck, we will support you over email.

  - title: What if I regret my purchase?
    description: Don't worry. If you decide Volca is not the right choice for you, you can request a refund within 14 days and we will give you all your money back.

  - title: How is Volca hosted?
    description: Volca is hosted on AWS using a cloud native approach. We believe in utilizing the full potential of one cloud provider and AWS is our provider of choice. You are however free to modify the template to run on any cloud provider that works for you.

  - title: How is Volca deployed?
    description: All of the infrastructure required to run Volca is defined using AWS CDK and deploys to an AWS account of your choosing. By default, GitHub Actions are configured to deploy to your environments when pushing code into your GitHub repository.

  - title: Who built Volca?
    description: Volca was built by Oskar and Karl, two full stack developers with a combined programming experience of 20 years. They have worked on everything from fast growing apps to huge enterprise systems and all of their learnings have been poured into the development of Volca.

  - title: Why did you build Volca?
    description: After building software products for the last 10 years, we noticed that there is a huge startup time when building something from scratch. So we took all the components that we kept rebuilding for each project and put them into a single template that anyone can use to kick start their development.

#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get tutorials and inspiration for building your own SaaS # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).

#-------------------------------
# Footer Settings
social:
  - {
      icon: "ion-logo-twitter",
      color: "#55acee",
      label: Twitter,
      link: "https://twitter.com",
    }
  - {
      icon: "ion-logo-facebook",
      color: "#3b5999",
      label: Facebook,
      link: "https://facebook.com",
    }
  - {
      icon: "ion-logo-pinterest",
      color: "#bd081c",
      label: Pinterest,
      link: "https://pinterest.com",
    }
  - {
      icon: "ion-logo-dribbble",
      color: "#ea4c89",
      label: Dribbble,
      link: "https://dribbble.com",
    }
  - {
      icon: "ion-logo-instagram",
      color: "#e4405f",
      label: Instagram,
      link: "https://instagram.com",
    }
  - {
      icon: "ion ion-logo-vimeo",
      color: "#1393cd",
      label: Vimeo,
      link: "https://vimeo.com",
    }

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.
