---
#-------------------------------
# Site Settings
title: Volca - Node and React SaaS Template
logo: /images/logo-light.svg
author: Volca
description: Clancy is a elegant portfolio theme for Jekyll.

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"
    - title: "Contact"
      url: "/contact/"
    - title: "Elements"
      url: "/elements/"

#-------------------------------
# Hero Settings
hero:
  hero__title: Node and React SaaS Template
  hero__description: Create your SaaS using proven Node and React patterns that accelerate your development and deployment speed.

#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Features
  portfolio__gallery:
    - icon: ion-ios-build
      title: CI/CD
      description: Deploy with confidence from the start with a solid CI/CD setup

    - icon: ion-ios-lock
      title: Secure
      description: Built with best practice security

    - icon: ion-ios-card
      title: Subscriptions
      description: Enable your users to subscribe to your service

    - icon: ion-ios-briefcase
      title: Projects
      description: Enable your users to create projects and invite their team

    - icon: ion-ios-key
      title: Authentication
      description: Secure and reliable authentication out of the box

    - icon: ion-ios-pulse
      title: Monitoring
      description: Make sure your SaaS is running smoothly at all times

    - icon: ion-ios-search
      title: Logging
      description: Find and remedy production issues quickly

    - icon: ion-ios-cash
      title: Free Tier
      description: Free at rest infrastructure - no usage, no cost

    - icon: ion-ios-code
      title: Open Source
      description: Our core functionality is available open source

#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get tutorials and inspiration for building your own SaaS # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).

#-------------------------------
# Footer Settings
social:
  - {
      icon: "ion-logo-twitter",
      color: "#55acee",
      label: Twitter,
      link: "https://twitter.com",
    }
  - {
      icon: "ion-logo-facebook",
      color: "#3b5999",
      label: Facebook,
      link: "https://facebook.com",
    }
  - {
      icon: "ion-logo-pinterest",
      color: "#bd081c",
      label: Pinterest,
      link: "https://pinterest.com",
    }
  - {
      icon: "ion-logo-dribbble",
      color: "#ea4c89",
      label: Dribbble,
      link: "https://dribbble.com",
    }
  - {
      icon: "ion-logo-instagram",
      color: "#e4405f",
      label: Instagram,
      link: "https://instagram.com",
    }
  - {
      icon: "ion ion-logo-vimeo",
      color: "#1393cd",
      label: Vimeo,
      link: "https://vimeo.com",
    }

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.
